### ISSUE TITLE
Question: Excel examples?

### ISSUE THREAD

**Issue by nidoro** [coin-or/Cmpl#4]
Hi there,

I know it is possible to read/write xlsx files in CMPL, but I couldn't find actual examples. Yes, there is the example in the CMPL PDF manual, but I was wondering if the actual files of the example are available somewhere, and where can I find more examples. I think it is a super cool feature, and would like to learn more about it.

Thanks.

**Comment by MikeSteglich** [comment]
Hi Nidoro,

I apologise for the delayed reply. There are sample files available on Coliop.org (section Download) including CmplXlsData example.
