### ISSUE TITLE
First variable (x[1]) in SCIP solution via Coliop ignores its upper bound solving BQP

### ISSUE THREAD

**Issue by JohannesJordaan** [coin-or/Cmpl#6]
I am solving a binary quadratic program (BQP) with SCIP selected as the solver.
In the Coliop IDE, the problem appears to converge, but the very first variable, x[1], runs up far beyond its upper bound.
The CMPL program calls the SCIP implementation of SCIPOptSuite 8.0.3.
The same problem solves via Matlab calling scip.mexw64 (presumably older than the above) obtained from Opti Toolbox.

**Comment by MikeSteglich** [comment]
Could you send the problem file directly to me?
