### ISSUE TITLE
When outputting solution to file, last variable is missing

### ISSUE THREAD

**Issue by OwenAuger** [coin-or/Cmpl#7]
When running CMPL with the command line tool and outputting the solution to XML, CSV, or ASCII files, the last variable is missing from the solution file.

I have attached `CMPL Variable Missing from Solution.zip`.
[CMPL Variable Missing from Solution.zip](https://github.com/coin-or/Cmpl/files/13969086/CMPL.Variable.Missing.from.Solution.zip)

This contains:
- `Dummy.cmpl`
- `DummySolution.xml`

`Dummy.cmpl` contains a simple model with two variables (x & y) including header `%solution DummySolution.xml`

`DummySolution.xml` is the solution file produced after solving the model with this command:
`cmpl Dummy.cmpl`

In `DummySolution.xml`, the second variable (y) is missing from `<variables>`.
Also these XML elements do not appear to be closed correctly:

- `<CmplSolutions>`
- `<solution>`
- `<variables>`

If I output to CSV or ASCII instead, the second variable (y) is also missing.

**Comment by MikeSteglich** [comment]
Cmpl converts your two constraints into upper bounds for the variables. Therefore, no constraints are created. This issue causes that problem. 
BTW, Sorry for the late reply.
